name: flutter_animation
description: "Effortlessly animate views or list items with AnimationView by selecting an animation type. Options include: none, fadeIn, scale, slideRTL, slideLTR, slideUp, flip, bounce, scaleLTR, scaleCenterZoomOut. Enhance your UI seamlessly! 🚀✨"
version: 0.0.1
homepage: https://github.com/Zaveri21/flutter_animation
repository: https://github.com/Zaveri21/flutter_animation
issue_tracker: https://github.com/Zaveri21/flutter_animation/issues

environment:
  sdk: ">=2.18.6 <4.0.0"
  #sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.0  

platforms:
  android:
  ios:

funding:
  - https://buymeacoffee.com/vishaljhaveri